# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_auto_20161130_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='slug',
            field=models.SlugField(default='unnamed', unique=True, verbose_name='Unique marketplace name'),
        ),
    ]
